### ISSUE TITLE
Documentation Contributions are Open! #Hacktoberfest2020

### ISSUE THREAD

**Issue by sakshamsingh01** [SakshamSingh-v2/First-Projects#13]
**Contributions are open for making simple documentation for installing the specific programming language and setting up a development environment,**

For eg. There is a Python folder. An instructions.md file is needed inside the python folder which describes how to install python and set up a development environment (like venv).

Instructions for installation and setting up are needed for all programming languages which are present in this repo.

The instructions must be beginner friendly and screenshots along with steps will be appreciated.
(For adding image files, create an assets folder)

If you want to contribute specify the programming language you want to work upon in comments.

Let's celebrate Hacktoberfest 2020 together!

**Comment by sakkshm** [comment]
Hi @SakshamSingh-v2 ,I would like to do it for Python. Please assign it to me.

**Comment by sakshamsingh01** [comment]
Done! @sakkshm !

**Comment by sakkshm** [comment]
I made the Python Installation guide in #18

**Comment by sakshamsingh01** [comment]
Great work @sakkshm ! I have merged your PR. **Please add your name in CONTRIBUTORS.md** :-)

**Comment by abhinvag** [comment]
Hi, @SakshamSingh-v2 I want to do it for JAVA, please assign it to me.

**Comment by sakshamsingh01** [comment]
Done! @wraith-0 you can work upon it. Make sure to have a look at installation.md file present in the python folder to get a better understanding of what is needed

**Comment by VidyaSrivatsan** [comment]
I would like to create instruction manual for DART

**Comment by sakshamsingh01** [comment]
Great! @VidyaSrivatsan . You can contribute in it. Make sure to have a look at installation.md file present in the python folder to get a better understanding of what is needed

**Comment by VidyaSrivatsan** [comment]
Sure @SakshamSingh-v2 : I had a look at the installation.md file. The installation guide for DART will be in similar lines.
