### ISSUE TITLE
Write How-To Instructions for beginners

### ISSUE THREAD

**Issue by sakshamsingh01** [SakshamSingh-v2/First-Projects#2]
Write instructions about how to fork a repository, clone it, push new changes and create pull requests.
Make sure to keep the instructions Beginner Friendly and add some screenshots also!

**Lets help the beginners to make their way in OpenSource.**

#Hacktoberfest

**Comment by Abhicoder03** [comment]
Hey, I can work on this. Please assign this to me.

**Comment by vishalGUPTA-vg** [comment]
what we have to do in contributing file

**Comment by sakshamsingh01** [comment]
Sure @Abhicoder03! You can work on it! Make sure to add clear steps with some screenshots. So that a beginner can understand easily.

**Comment by Abhicoder03** [comment]
Okay @SakshamSingh-v2.

**Comment by sakshamsingh01** [comment]
A good documentation was made by @vikassethi09. This issue is closed now. 
**You can find easy opportunities to contribute in issue #1 **

Have a look at it. #1
