### ISSUE TITLE
Embrace those Contributors!

### ISSUE THREAD

**Issue by sakshamsingh01** [SakshamSingh-v2/First-Projects#36]
Right now, CONTRIBUTORS.md file is a plain list with the name of contributors. Format the contributors.md file, add a proper structure and make it look visually appealing. Let other's know who contributed. 🥇

**Comment by anagosseen** [comment]
Hi @SakshamSingh-v2 , I would like to contribute to this.

**Comment by sakshamsingh01** [comment]
Go on @anagosseen !

**Comment by anagosseen** [comment]
Thank you @SakshamSingh-v2, pull has been submitted.
